### ISSUE TITLE
Hopper does not place seeds when moved by magnets

### ISSUE THREAD

**Issue by SpiderBee1** [VazkiiMods/crucial2#139]
I compared the behaviour in Crucial 2 to behaviour in standalone quark w/ oddities. It seems to only be broken with crucial 2. 
It's possible that something broke when crates were added but I think it's more likely that multiple mods are conflicting over hopper behaviour or something like that.

**Comment by artemisSystem** [comment]
Happens because of the waterlogging hoppers feature from Inspirations

**Comment by Hubry** [comment]
Looks like Quark inits the map of block -> behavior on class init, and registry replacement running later results in the map having the wrong hopper block instance.

**Comment by artemisSystem** [comment]
Fixed by 6f449f9a5d04b194d93c6d26763acb9635cd19dd for now
