### ISSUE TITLE
Speleothem Cave "Biome?" Spawning very, very few ores.

### ISSUE THREAD

**Issue by SleepyEmber** [VazkiiMods/crucial2#147]
![2021-07-02_21 28 54](https://user-images.githubusercontent.com/18420537/124340615-687b2900-db84-11eb-812e-cf3d17d95fe4.png)
![2021-07-02_21 28 58](https://user-images.githubusercontent.com/18420537/124340616-687b2900-db84-11eb-978e-1a8f2bb8dc88.png)
![2021-07-02_21 30 47](https://user-images.githubusercontent.com/18420537/124340617-687b2900-db84-11eb-9c7a-1368cba96687.png)
![2021-07-02_21 30 50](https://user-images.githubusercontent.com/18420537/124340618-687b2900-db84-11eb-886f-28d1f62ae6f5.png)
![2021-07-02_21 32 13](https://user-images.githubusercontent.com/18420537/124340619-6913bf80-db84-11eb-9c28-b0b4780c041a.png)

While these screenshots were taken in an edited form of Crucial 2, I double-checked on Crucial 2 1.2.2, and it reproduces this. (Realistic gen on and off)

I have the seed and can provide more info.

**Comment by Partonetrain** [comment]
We determined this to be in `minecraft:mountains` biomes specifically.

**Comment by evanbones** [comment]
Can confirm, I think it's an issue with the Crucial worldgen datapack

**Comment by Vazkii** [comment]
Hm. It probably has something to do with the fact the data pack scales up
mountains, which might mess with the ore generation.

**Comment by evanbones** [comment]
The datapack makes references to 1.17 exclusive materials, which may be causing problems (glow lichen for example)

**Comment by evanbones** [comment]
Fixed in https://github.com/VazkiiMods/crucial2/pull/174
