### ISSUE TITLE
Infinite Elytra Durability by crafting into Elytra Wings

### ISSUE THREAD

**Issue by Partonetrain** [VazkiiMods/crucial2#151]
![image](https://user-images.githubusercontent.com/19861808/124841232-6208fa80-df52-11eb-99a0-e9a4f0147804.png)
![image](https://user-images.githubusercontent.com/19861808/124841377-b613df00-df52-11eb-9806-017fd51dbce7.png)

This is a Customizable Elytra issue but I figured I would put it here too since it could probably be resolved with crafttweaker/datapack
https://github.com/Hidoni/CustomizableElytra/issues/8

**Comment by evanbones** [comment]
Fixed in latest Customizable Elytra update
