### ISSUE TITLE
Changes for JEI notes

### ISSUE THREAD

**Issue by FynnWaelsing** [VazkiiMods/crucial2#172]
Just a few things that I thought were worth changing for the sake of clarity/correctness in the JEI notes:

Entrails: "Can be traded for with a butcher villager" --> "Can be acquired by trading with a butcher villager."

Cured Jerky: Should it state whether it adds 10 seconds of Speed when eaten?

Glimmer Gravel: Should it state that it falls when you step on it?

Basaltic Magma: Should it state that it creates a bubble column like vanilla magma blocks? Also worth adding that this and the vanilla magma can now keep striders warm.

Quartz Glass: Could mention that this glass is blast-resistant.

**Comment by artemisSystem** [comment]
Adding on to this, i think i saw the brown mushroom cluster (?) mention that you could get it from *red* mushrooms, that should probably be brown
