### ISSUE TITLE
Forgery should be updated to RC2

### ISSUE THREAD

**Issue by unascribed** [VazkiiMods/crucial2#178]
Heyo. I noticed that the new release of Crucial 2 updated to Forgery v1.3.5 RC1. (I'm the author of Forgery and Fabrication.)

There's a critical bug in RC1 that makes in-game reconfiguration nonfunctional by saving the configs incorrectly, making any user changes be lost as soon as the game is restarted.

Additionally, a joke feature is enabled by default due to a mistake backporting changes from the 1.17 branch. (You are affected because [the concerned feature is set to `unset` in Crucial 2's config](https://github.com/VazkiiMods/crucial2/blob/37a9abb/config/forgery/features.ini#L359-L360) and your profile is at least `light`.) The joke feature causes chests to randomly (~1/20 chance) render with additive blending, making them appear transparent and "glowy". It refers to a common state leak bug in pre-RenderLayer versions of Minecraft.

Both of these things are fixed in RC2. Please update when you can. Sorry for the inconvenience and the fact these bugs slipped through at all.

**Comment by Vazkii** [comment]
I think you got this wrong because the pack is definitely running RC2 :P

**Comment by unascribed** [comment]
Guess I messed up reading Git. Sorry.
