### ISSUE TITLE
Copper Ore doesn't drop an item when mined

### ISSUE THREAD

**Issue by NES-Elliott** [VazkiiMods/crucial2#185]
Exactly as title says, tested with stone and iron pickaxes.

**Comment by Vazkii** [comment]
Do you have CreateTweaker and ContentTweaker installed?

**Comment by thalio08** [comment]
i actually had same issue on server while singleplayer is working fine
i have crucial2 + create and flywheel
now i have installed createtweaker and item drop texture texture is missing
singleplayer world still no issue

**Comment by thalio08** [comment]
> i actually had same issue on server while singleplayer is working fine
> i have crucial2 + create and flywheel
> now i have installed createtweaker and item drop texture texture is missing
> singleplayer world still no issue

full reinstall soveld the issue
crucial2+create+flywheel+createtweaker

**Comment by Vazkii** [comment]
This happens when you load a world without CreateTweaker, and then load it after. Doing it in this order causes the world to think the Crucial2 data pack is invalid (because it is without CreateTweaker). You can either recreate the world or rename the data pack.

**Comment by ZephyrWindSpirit** [comment]
That answers my question that I was just hunting up. I didn't realize immediately that I needed createtweaker, and encountered the same problem. Also thought that zinc had to be enabled so 'headsmack derp', I had renabled it in the config for my world. Lesson learned!
