### ISSUE TITLE
Rendering issues with sodium and create

### ISSUE THREAD

**Issue by bucketBrian** [VazkiiMods/crucial2#198]
when both sodium reforged (Any version) and create (above 0.3.2b) loading, all create block have animation (like gears, and stone mill, which only unanimated parts will visible) will be invisible.
strange thing is when change the sodium's setting "Use Block Face Culling" (whatever disable or enable it), all existing create block will be visible, but new placed blocks will still invisible. so it can't be a ways of resolution.
please don't make it eventually become a "either or".

**Comment by funketh** [comment]
as a reference for others:
https://github.com/Creators-of-Create/Create/issues/2115
