### ISSUE TITLE
Removed features still have achievements present

### ISSUE THREAD

**Issue by CosmicParticl** [VazkiiMods/crucial2#201]
Some achievements having to do with disabled content, like the twisted wood from Architect's Palette and elephants from Alex's Mobs are still present despite being unobtainable. Additionally, some of the descriptions in Architect's palette achievements do not reflect how they are obtained in the pack

**Comment by Vazkii** [comment]
This seems like an incorrect pack installation, because every Architect's Palette advancement is removed.

**Comment by CosmicParticl** [comment]
Interesting, in that case I'll try deleting and reinstalling the pack.
