### ISSUE TITLE
Suggestion: Option to go back to vanilla splash text

### ISSUE THREAD

**Issue by QuietObserver** [VazkiiMods/crucial2#221]
Not that I disagree with what the current splash text says, but text like 'Stand up for equality in your community!' does not have the same feel as 'Play Minecraft, Watch Topgear, Get Pig!'

**Comment by Vazkii** [comment]
![image](https://user-images.githubusercontent.com/1794735/132397355-5796464a-dfe5-47c2-b82b-a6c1c535fa2d.png)
you can delete this file in the pack files if you want to remove the custom ones
