### ISSUE TITLE
server pack mods folder

### ISSUE THREAD

**Issue by Shrilliam** [VazkiiMods/crucial2#222]
I can't get the mods to upload to my server host correctly, maybe it's because the mods are in an excel sheet? If anybody can help me fix this that would be great.
![image](https://user-images.githubusercontent.com/90066726/132058599-3247c953-4ebf-42ac-92b1-1f6e0c254fb2.png)

**Comment by megatrook** [comment]
you have to run setup_server.bat to have it install all the mods :)

**Comment by Shrilliam** [comment]
thank you!
