### ISSUE TITLE
[Question] Botania integration 

### ISSUE THREAD

**Issue by g-rock84** [VazkiiMods/crucial2#231]
So, first off, thank you so much for this modpack and all the hard work you have and are still putting into it! 

I apologize if this is a silly question as this is literally called a vanilla style modpack and it has been stated many times that the mods included fit closely with vanilla. That being said, you have the optional Create integration. Why is there no optional Botania integration? How much would it effect the balance of the pack if I added it? I'm definitely not asking for it to be implemented. I'll leave that to your (Vazkii and company) better judgment, but I would appreciate maybe some tweaks I could do to better integrate it myself. I am familiar with zenscripts and data packs and I'm not afraid to mess with them. I would just appreciate some professional advice on how to best make it fit. 

Thank you for your time!

**Comment by Vazkii** [comment]
There's a pack for it in development unofficially. Might get it merged in when it's done.
