### ISSUE TITLE
[1.3.5] Shulker Box Tooltip Bug

### ISSUE THREAD

**Issue by itsdeelee** [VazkiiMods/crucial2#239]
The tool tip area under where it says Minecraft shows the icons (randomly placed) of the the contents inside a Shulker Box.
I even tested it with loading a brand new instance of the modpack (1.3.5) and the bug(?) still occurs.
Here's the image:
![javaw_a1KCgHFpmZ](https://user-images.githubusercontent.com/23088649/134830575-9861a313-4f64-47ea-b8a0-c67d73c9984c.png)

**Comment by artemisSystem** [comment]
looks like bundles plus is rendering the bundles view for shulker boxes too. might be able to turn it off in the config

**Comment by itsdeelee** [comment]
Turning off the tooltips in the config file seems to have fixed the issue!
Thank you.
