### ISSUE TITLE
placing bamboo torch corrupts world

### ISSUE THREAD

**Issue by stargreens** [VazkiiMods/crucial2#242]
i had the modpack at the default settings, only change is i swapped halogen for optifine

placed a bamboo torch down, and the game crashed. upon reloading, the game would refuse to load the world, and then crash again. loading screen only showed half of the grey square

crash report:
[crash-2021-09-29_15.52.52-client.txt](https://github.com/VazkiiMods/crucial2/files/7249536/crash-2021-09-29_15.52.52-client.txt)

**Comment by bconlon1** [comment]
Can confirm this is an issue with the base pack, basically breaks a world unless you're on a server and can use fill commands to get rid of it from console.

**Comment by stargreens** [comment]
> see #253

thank you!
