### ISSUE TITLE
Bamboo Torches causing a Crash

### ISSUE THREAD

**Issue by FynnWaelsing** [VazkiiMods/crucial2#258]
Bamboo torches from Bamboo Blocks appear to be causing a crash, with multiple individuals in the Discord channel reporting this bug. It appears to be [this issue](https://github.com/team-abnormals/bamboo-blocks/issues/47) on the Bamboo Blocks Github.

**Comment by bconlon1** [comment]
If anyone encounters this issue on multiplayer and needs a fix for it, I was able to find a way to remove the torch through the server console:
- first I downloaded the playerdata of the player who placed the torch
- then I used NBTExplorer to find the players position
- I went to the server console
- I typed in a fill command with the corner positions being made to be relative to the player's position (the first corner i subtracted from the player's position for each coordinate by like 5 and then the second corner i added 5).
- The fill command: `/fill [corner1x] [corner1y] [corner1z] [corner2x] [corner2y] [corner2z] minecraft:air replace bamboo_blocks:bamboo_torch` (the id of the bamboo torch can be replaced with whatever the actual id is if its a torch variant)
