### ISSUE TITLE
Supplementaries Wild Flax can generate despite being disabled.

### ISSUE THREAD

**Issue by Ceres-The-Cat** [VazkiiMods/crucial2#269]
Playing Crucial 2 + Create I encountered Wild Flax on the edge of a desert, which drops Flax Seeds. The Flax Seeds, and their Flax crop, seem to be disabled, as they don't appear in JEI.

Steps to reproduce:
1. Generate a world in Crucial 2 + Create with the following seed:
-4624889681616017103
2. Go to the following coordinates
X 1158, Y 63, Z 1357
3. Enter survival mode and break the Wild Flax at that location.

Additional Wild Flax can be located in the same seed around X 1405, Y 64, Z 1371

**Comment by Vazkii** [comment]
https://github.com/VazkiiMods/crucial2/commit/461765af10e0d0ac7c26007da947772b7a0849b9
