### ISSUE TITLE
Update the RS - More Villagers datapack

### ISSUE THREAD

**Issue by TelepathicGrunt** [VazkiiMods/crucial2#272]
When you got time, could you please update the RS - More Villagers compat datapack? I had a typo in it that crashed mushroom villages: https://github.com/TelepathicGrunt/RepurposedStructures/issues/153

The updated v2 fixed datapack can be downloaded here: https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.8

I know mushroom villages are disabled by default in crucial 2 but I don't want someone to turn them back on and then complain to you about it crashing and then you all waste time debugging what the heck is going on lol. Sorry about that but I'll keep you updated whenever more game crashing bugs arise from my mods.

**Comment by Vazkii** [comment]
More Villagers isn't in the pack lol
