### ISSUE TITLE
Cannot build a Nether Portal on Single Player World

### ISSUE THREAD

**Issue by noobilly** [VazkiiMods/crucial2#276]
When I made my first nether portal by lighting up the obsidian with Flint and Steel under a cave on my single player's [save](https://drive.google.com/file/d/1gI6qAHxyMoJJ6rHp7wHDzI38kxGFs0YU/view), Minecraft crashed immediately([Minecraft Crash Report](https://github.com/VazkiiMods/crucial2/files/7455754/crash-2021-11-02_02.42.00-client.txt)).

 After that, I tried to open my single player's save but Mincraft kept crashing like [this](https://github.com/VazkiiMods/crucial2/files/7455734/crash-2021-11-02_03.06.41-client.txt). Then, I found that removing "magnesium-1.1.2.jar" from mods folder is able to let my open the save normally. However, after putting back the "magnesium-1.1.2.jar" to mods folder, I was not able to open the save again.

Therefore, maybe editing the code from [magnesium ](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/tree/main/Legacy%20Sodium) or finding an alternative mod of magnesium can be the solution of my issue.

**Comment by Vazkii** [comment]
This has already been fixed but if you're still getting the issue, changing `customPortalColor` in the `inspirations-client.toml` file to false will solve it.
