### ISSUE TITLE
Raw Ore mod not working with create

### ISSUE THREAD

**Issue by SummaryG** [VazkiiMods/crucial2#296]
I know this pack doesn't have create added by default but the easy integration is mentioned. The Raw ores from the Iron and Gold from 1.17 mod don't crush into crushed iron or gold ore. I'm not sure if its possible but could you fix the recipe for those of us who decided to add the create mod.

**Comment by yuri0r** [comment]
did you also add flywhell and [CreateTwekaer](https://www.curseforge.com/minecraft/mc-mods/createtweaker)?

for me everything works right out the box.

**Comment by SummaryG** [comment]
> did you also add flywhell and [createtweaker](https://www.curseforge.com/minecraft/mc-mods/createtweaker)?
> 
> for me everything works right out the box.

yeah i missed createtweaker like an idiot its my fault im closing this thread sorry for wasting time
