### ISSUE TITLE
Right HUD Bar don't appear

### ISSUE THREAD

**Issue by Luigi-121** [VazkiiMods/crucial2#351]
The hunger bar and the underwater stamina don't appear

**Comment by fruithats** [comment]
had this issue for a few days with no luck trying to fix it, the culprit for me ended up being the 'embeddiumextension' mod -- i managed to narrow it down to that one and after removing it all the HUD elements appear as they should. hope this helps!

**Comment by martyroi** [comment]
> had this issue for a few days with no luck trying to fix it, the culprit for me ended up being the 'embeddiumextension' mod -- i managed to narrow it down to that one and after removing it all the HUD elements appear as they should. hope this helps!

Updating that specific mod seems to fix the problem. Thank you for this!
